# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/Zen.sln
    - name: Build
      run: dotnet build --no-restore src/Zen.sln --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal src/Zen.sln --configuration Release
    - name: Publish the package to NuGet
      run: dotnet nuget push src/Zen.Z80/bin/Release/*.nupkg -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Publish the package to GitHub
      run: dotnet nuget push src/Zen.Z80/bin/Release/*.nupkg -k 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 -s https://nuget.pkg.github.com/stevehjohn/index.json --skip-duplicate
